import itertools
import typing as t
import asyncio
from abc import ABC, abstractmethod
from enum import StrEnum

from pluginable_core import exc
from pluginable_core.event import EventHandler, Event
from pluginable_core.plugin import PluginsBearer, Plugin


_AppPluginT = t.TypeVar("_AppPluginT", bound="AppPlugin", covariant=True)


class MainFlowEventType(StrEnum):
    APP_CLOSE_REQUEST = "APP_CLOSE_REQUEST"


class MainFlowEvent(Event):
    EVENT_TYPE: MainFlowEventType


class AppCloseRequestEvent(MainFlowEvent):
    EVENT_TYPE: t.Literal[
        MainFlowEventType.APP_CLOSE_REQUEST
    ] = MainFlowEventType.APP_CLOSE_REQUEST


class PluginableApp(
    PluginsBearer,
    EventHandler[MainFlowEvent],
):
    def __init__(self):
        super().__init__()

        self._run_lock = asyncio.Lock()

    @property
    def running(self):
        return self._run_lock.locked()

    async def before_event_loop(self) -> None:
        await super().before_event_loop()
        if not self.context_entered:
            raise exc.MissingContext(
                f"You are unable to run {self} for now. Please ensure context "
                f"when dealing with {self.__class__.__name__} context "
                f"dependent methods."
            )

        self.emit(AppRunEvent())

    async def run(self) -> None:
        plugin_runners = (
            asyncio.create_task(plugin.run()) for plugin in self.plugins
        )
        event_loop = asyncio.create_task(self.run_event_loop())

        first_done, _ = await asyncio.wait(
            (
                event_loop,
                plugins_wait := asyncio.create_task(
                    asyncio.wait(
                        plugin_runners, return_when=asyncio.FIRST_EXCEPTION
                    )
                ),
            ),
            return_when=asyncio.FIRST_COMPLETED,
        )

        if first_done != event_loop:
            AppCloseRequestEvent().emit_to(self)

        exceptions = []

        try:
            await event_loop
        except Exception as e:
            exceptions.append(e)

        done, pending = await plugins_wait
        for task in itertools.chain(done, pending):
            try:
                await task
            except Exception as e:
                exceptions.append(e)

        if len(exceptions) == 0:
            return
        if len(exceptions) == 1:
            raise exceptions[0]

        raise ExceptionGroup(
            "Many plugins or app raised exceptions", exceptions
        )

    async def after_event_loop(
        self, exception: BaseException | None = None
    ) -> bool:
        self.emit(AppCloseEvent())
        return await super().after_event_loop(exception)

    async def on_app_close_request(self, *, event: AppCloseRequestEvent):
        raise exc.EventLoopExit()


class AppPlugin(Plugin[PluginableApp], EventHandler["AppEvent"], ABC):
    async def on_app_run(self):
        pass

    async def on_app_close(self):
        raise exc.EventLoopExit()


class AppEventType(StrEnum):
    APP_RUN = "APP_RUN"
    APP_CLOSE = "APP_CLOSE"


class AppEvent(Event[AppPlugin]):
    """
    Event generated by App instance
    """

    EVENT_TYPE: AppEventType


class AppRunEvent(AppEvent):
    """
    Event generated on App run
    """

    EVENT_TYPE: t.Literal[AppEventType.APP_RUN] = AppEventType.APP_RUN


class AppCloseEvent(AppEvent):
    """
    Event generated on App close
    """

    EVENT_TYPE: t.Literal[AppEventType.APP_CLOSE] = AppEventType.APP_CLOSE
